apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: practice
  name: practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practice
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: practice
    spec:
      containers:
      - env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: SECRET_KEY
              name: practice-secrets
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              key: MONGO_URI
              name: practice-secrets
        image: tagepic/3d-practice-website:latest
        imagePullPolicy: Always
        name: website
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 1